#!/bin/sh
s() {
  n=$1; i=1; while [ "$n" -le $2 ]; do
    echo "$n"; : $((n+=i))
  done
} # seq
[ "$1" -eq 4 ] && {
  echo '2'; exit 0
}
for i in $(s 1 $(($1/3))); do
  [ "$((i*i))" -eq "$1" ] && {
    echo "$i"; exit 0
  } 
done
printf 'Cannot calculate Square Root of %s
It may not be a whole number..\n' "$1"; exit 1
