#!/bin/sh
IFS=""
[ "$RANP" ] && {
  ran="$(${RANP})"
} || [ -d $PWD/../ran ] && {
  ran="$($PWD/../ran/ran)"
} || {
  printf 'Location of psh-prng unknown... 
Please Set $RANP to its location...\n'
  exit 1
}
gran() {
  ran="$(${RANP:-$PWD/../ran/ran} $2)"
  # $ran -eq $ran -- checks if number 
  until [  "$ran" -gt 1 -a "$ran" -eq "$ran" -a "$ran" -lt "$1" ]; do
    ran="$(${RANP:-$PWD/../ran/ran} $2)"
    until [ "${ran%0}" = "$ran" ]; do
      ran="${ran%0}" 
    done
    until [ "${#ran}" -le "${#1}" ]; do
      ran="${ran#?}";
      until [ "${ran#0}" = "${ran}" ]; do
        ran="${ran#0}"
      done
    done
  done
  echo "$ran"
}
ran=$(gran "$1"); s="!"; n=0; while [ "$s" = "!" ]; do
  #echo "$ran $(($1/3))"
  [ "$ox" ] || ox="$ran"
  [ "$ox" -a "$ox" -eq "$ran" ] && {
    ran="$(gran $1)"
  }
  #echo "$ox $ran $1 $(($1/ox)) $(($1/ran)) $((ran*ran)) $((ox*ox)) -- $n"
  [ "$((ran*ran))" -eq "$((ox*ox))" ] && {
    : $((n+=1))
    #echo "-- $n "
  }
  ox="$ran"
  [ "$ran" -le 1 ] && {
    ran="$(gran $1)"
  } || {
    #echo "-- $ran $(($1/3))"
    [ "$((ran*ran))" -eq "$1" ] && {
      s=":"
    } || {
      [ "$((ran*ran))" -gt "$1" ] && {
        [ "$(($1/ran))" -eq 1 ] && : $((ran+=1))
        ran=$((($1/ran +ran)/2))
        #echo "? $ran"
      } || {
        ran=$((ran*ran))
      }
    }
  }
done
echo "$ran | $n"
